using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FinalYearProject
{
    class PlayerData
    {
        public DateTime Date { get; set; }
        public int PlayerID { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public string Team { get; set; }
        public int TeamID { get; set; }
        public string Opposition { get; set; }
        public int OppositionID { get; set; }
        public string Venue { get; set; }
        public int PositionID { get; set; }
        public int Appearances { get; set; }
        public int TimePlayed { get; set; }
        public int Starts { get; set; }
        public int SubstituteOn { get; set; }
        public int SubstituteOff { get; set; }
        public int Goals { get; set; }
        public int FirstGoal { get; set; }
        public int WinningGoal { get; set; }
        public int ShotsOnTargetIncGoals { get; set; }
        public int ShotsOffTargetIncWoodwork { get; set; }
        public int BlockedShots { get; set; }
        public int PenaltiesTaken { get; set; }
        public int PenaltyGoals { get; set; }
        public int PenaltiesSaved { get; set; }
        public int PenaltiesOffTarget { get; set; }
        public int PenaltiesNotScored { get; set; }
        public int DirectFreeKickGoals { get; set; }
        public int DirectFreeKickOnTarget { get; set; }
        public int DirectFreeKickOffTarget { get; set; }
        public int BlockedDirectFreeKick { get; set; }
        public int GoalsFromInsideBox { get; set; }
        public int ShotsOnfromInsideBox { get; set; }
        public int ShotsOfffromInsideBox { get; set; }
        public int BlockedShotsfromInsideBox { get; set; }
        public int GoalsFromOutsideBox { get; set; }
        public int ShotsOnfromOutsideBox { get; set; }
        public int ShotsOfffromOutsideBox { get; set; }
        public int BlockedShotsOutsideBox { get; set; }
        public int HeadedGoals { get; set; }
        public int HeadedShotsOnTarget { get; set; }
        public int HeadedShotsOffTarget { get; set; }
        public int HeadedBlockedShots { get; set; }
        public int LeftFootGoals { get; set; }
        public int LeftFootShotsOnTarget { get; set; }
        public int LeftFootShotsOffTarget { get; set; }
        public int LeftFootBlockedShots { get; set; }
        public int RightFootGoals { get; set; }
        public int RightFootShotsOnTarget { get; set; }
        public int RightFootShotsOffTarget { get; set; }
        public int RightFootBlockedShots { get; set; }
        public int OtherGoals { get; set; }
        public int OtherShotsOnTarget { get; set; }
        public int OtherShotsOffTarget { get; set; }
        public int OtherBlockedShots { get; set; }
        public int ShotsClearedOffLine { get; set; }
        public int ShotsClearedOffLineInsideArea { get; set; }
        public int ShotsClearedOffLineOutsideArea { get; set; }
        public int GoalsOpenPlay { get; set; }
        public int GoalsFromCorners { get; set; }
        public int GoalsFromThrows { get; set; }
        public int GoalsFromDirectFreeKick { get; set; }
        public int GoalsFromSetPlay { get; set; }
        public int GoalsFromPenalties { get; set; }
        public int AttemptsOpenPlayonTarget { get; set; }
        public int AttemptsfromCornersonTarget { get; set; }
        public int AttemptsfromThrowsonTarget { get; set; }
        public int AttemptsfromDirectFreeKickonTarget { get; set; }
        public int AttemptsfromSetPlayonTarget { get; set; }
        public int AttemptsfromPenaltiesonTarget { get; set; }
        public int AttemptsOpenPlayoffTarget { get; set; }
        public int AttemptsfromCornersoffTarget { get; set; }
        public int AttemptsfromThrowsoffTarget { get; set; }
        public int AttemptsfromDirectFreeKickoffTarget { get; set; }
        public int AttemptsfromSetPlayoffTarget { get; set; }
        public int AttemptsfromPenaltiesoffTarget { get; set; }
        public int GoalsasSubstitute { get; set; }
        public int TotalSuccessfulPassesAll { get; set; }
        public int TotalUnsuccessfulPassesAll { get; set; }
        public int Assists { get; set; }
        public int KeyPasses { get; set; }
        public int TotalSuccesfulPassesExclCrossesCorners { get; set; }
        public int TotalUnsuccesfulPassesExclCrossesCorners { get; set; }
        public int SuccesfulPassesOwnHalf { get; set; }
        public int UnsuccesfulPassesOwnHalf { get; set; }
        public int SuccesfulPassesOppositionHalf { get; set; }
        public int UnsuccesfulPassesOppositionHalf { get; set; }
        public int SuccessfulPassesDefensiveThird { get; set; }
        public int UnsuccessfulPassesDefensiveThird { get; set; }
        public int SuccesfulPassesMiddleThird { get; set; }
        public int UnsuccesfulPassesMiddleThird { get; set; }
        public int SuccesfulPassesFinalThird { get; set; }
        public int UnsuccesfulPassesFinalThird { get; set; }
        public int SuccesfulShortPasses { get; set; }
        public int UnsuccesfulShortPasses { get; set; }
        public int SuccesfulLongPasses { get; set; }
        public int UnsuccesfulLongPasses { get; set; }
        public int SuccessfulFlickOns { get; set; }
        public int UnsuccessfulFlickOns { get; set; }
        public int SuccesfulCrossesCorners { get; set; }
        public int UnsuccesfulCrossesCorners { get; set; }
        public int CornersTakeninclShortCorners { get; set; }
        public int CornersConceded { get; set; }
        public int SuccessfulCornersintoBox { get; set; }
        public int UnsuccessfulCornersintoBox { get; set; }
        public int ShortCorners { get; set; }
        public int ThrowInstoOwnPlayer { get; set; }
        public int ThrowInstoOppositionPlayer { get; set; }
        public int SuccessfulDribbles { get; set; }
        public int UnsuccessfulDribbles { get; set; }
        public int SuccessfulCrossesCornersLeft { get; set; }
        public int UnsuccessfulCrossesCornerLeft { get; set; }
        public int SuccessfulCrossesLeft { get; set; }
        public int UnsuccessfulCrossesLeft { get; set; }
        public int SuccessfulCornersLeft { get; set; }
        public int UnsuccessfulCornersLeft { get; set; }
        public int SuccessfulCrossesCornersRight { get; set; }
        public int UnsuccessfulCrossesCornersRight { get; set; }
        public int SuccessfulCrossesRight { get; set; }
        public int UnsuccessfulCrossesRight { get; set; }
        public int SuccessfulCornersRight { get; set; }
        public int UnsuccessfulCornersRight { get; set; }
        public int SuccessfulLongBalls { get; set; }
        public int UnsuccessfulLongBalls { get; set; }
        public int SuccessfulLayOffs { get; set; }
        public int UnsuccessfulLayOffs { get; set; }
        public int ThroughBall { get; set; }
        public int SuccessfulCrossesCornersInTheAir { get; set; }
        public int UnsuccessfulCrossesCornersInTheAir { get; set; }
        public int SuccessfulCrossesInTheAir { get; set; }
        public int UnsuccessfulCrossesInTheAir { get; set; }
        public int SuccessfulOpenPlayCrosses { get; set; }
        public int UnsuccessfulOpenPlayCrosses { get; set; }
        public int Touches { get; set; }
        public int GoalAssistCorner { get; set; }
        public int GoalAssistFreeKick { get; set; }
        public int GoalAssistThrowIn { get; set; }
        public int GoalAssistGoalKick { get; set; }
        public int GoalAssistSetPiece { get; set; }
        public int KeyCorner { get; set; }
        public int KeyFreeKick { get; set; }
        public int KeyThrowIn { get; set; }
        public int KeyGoalKick { get; set; }
        public int KeySetPieces { get; set; }
        public int Duelswon { get; set; }
        public int Duelslost { get; set; }
        public int AerialDuelsWon { get; set; }
        public int AerialDuelsLost { get; set; }
        public int GroundDuelsWon { get; set; }
        public int GroundDuelsLost { get; set; }
        public int TacklesWon { get; set; }
        public int TacklesLost { get; set; }
        public int LastManTackle { get; set; }
        public int TotalClearances { get; set; }
        public int HeadedClearances { get; set; }
        public int OtherClearances { get; set; }
        public int ClearancesOffTheLine { get; set; }
        public int Blocks { get; set; }
        public int Interceptions { get; set; }
        public int Recoveries { get; set; }
        public int TotalFoulsConceded { get; set; }
        public int FoulsConcededExcHandballsPen { get; set; }
        public int TotalFoulsWon { get; set; }
        public int FoulsWonInDangerAreaIncPens { get; set; }
        public int FoulsWonNotInDangerArea { get; set; }
        public int FoulWonPenalty { get; set; }
        public int HandballsConceded { get; set; }
        public int PenaltiesConceded { get; set; }
        public int Offsides { get; set; }
        public int YellowCards { get; set; }
        public int RedCards { get; set; }
        public int GoalsConceded { get; set; }
        public int GoalsConcededInsideBox { get; set; }
        public int GoalsConcededOutsideBox { get; set; }
        public int SavesMade { get; set; }
        public int SavesMadeFromInsideBox { get; set; }
        public int SavesMadeFromOutsideBox { get; set; }
        public int SavesFromPenalty { get; set; }
        public int Catches { get; set; }
        public int Punches { get; set; }
        public int Drops { get; set; }
        public int CrossesNotClaimed { get; set; }
        public int GKDistribution { get; set; }
        public int GKSuccessfulDistribution { get; set; }
        public int GKUnsuccessfulDistribution { get; set; }
        public int CleanSheets { get; set; }
        public int TeamCleansheet { get; set; }
        public int ErrorLeadingToGoal { get; set; }
        public int ErrorLeadingToAttempt { get; set; }
        public int ChallengeLost { get; set; }
        public int ShotsOnConceded { get; set; }
        public int ShotsOnConcededInsideBox { get; set; }
        public int ShotsOnConcededOutsideBox { get; set; }
        public int TeamFormation { get; set; }
        public int PositionInFormation { get; set; }
        public int Turnovers { get; set; }
        public int Dispossessed { get; set; }
        public int BigChances { get; set; }
        public int BigChancesFaced { get; set; }
        public int PassForward { get; set; }
        public int PassBackward { get; set; }
        public int PassLeft { get; set; }
        public int PassRight { get; set; }
        public int UnsuccessfulBallTouch { get; set; }
        public int SuccessfulBallTouch { get; set; }
        public int TakeOnsOverrun { get; set; }
        public int TouchesOpenPlayFinalThird { get; set; }
        public int TouchesOpenPlayOppBox { get; set; }
        public int TouchesOpenPlayOppSixYards { get; set; }
    }
}
